// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: appointment.sql

package database

import (
	"context"
	"time"
)

const createAppointment = `-- name: CreateAppointment :one
INSERT INTO appointments (user_id, appointment_date, completed)
VALUES ($1, $2, $3) RETURNING id, user_id, appointment_date, completed
`

type CreateAppointmentParams struct {
	UserID          int32
	AppointmentDate time.Time
	Completed       bool
}

func (q *Queries) CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRowContext(ctx, createAppointment, arg.UserID, arg.AppointmentDate, arg.Completed)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AppointmentDate,
		&i.Completed,
	)
	return i, err
}

const updateAppointment = `-- name: UpdateAppointment :one
UPDATE appointments SET completed = $1 WHERE id = $2 RETURNING id, user_id, appointment_date, completed
`

type UpdateAppointmentParams struct {
	Completed bool
	ID        int64
}

func (q *Queries) UpdateAppointment(ctx context.Context, arg UpdateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRowContext(ctx, updateAppointment, arg.Completed, arg.ID)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AppointmentDate,
		&i.Completed,
	)
	return i, err
}
