// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: habits.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const getHabits = `-- name: GetHabits :many
WITH days AS (
    SELECT generate_series($2::date, ($3::date - interval '1 day'), interval '1 day')::date AS day
)
SELECT
    d.day::date as day,
    COALESCE(COUNT(h.id) FILTER (WHERE h.completed = true), 0)::bigint AS completed_count
FROM days d
LEFT JOIN habits h
    ON h.habit_date::date = d.day
    AND h.user_id = $1
GROUP BY d.day
ORDER BY d.day
`

type GetHabitsParams struct {
	UserID  int32
	Column2 time.Time
	Column3 time.Time
}

type GetHabitsRow struct {
	Day            time.Time
	CompletedCount int64
}

func (q *Queries) GetHabits(ctx context.Context, arg GetHabitsParams) ([]GetHabitsRow, error) {
	rows, err := q.db.QueryContext(ctx, getHabits, arg.UserID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHabitsRow
	for rows.Next() {
		var i GetHabitsRow
		if err := rows.Scan(&i.Day, &i.CompletedCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHabitsOfDay = `-- name: GetHabitsOfDay :many
SELECT
    h.id,
    m.meal_name,
    CASE
        WHEN h.id IS NULL THEN 'pending'
        WHEN h.completed = true THEN 'completed'
        ELSE 'failed'
    END AS status
FROM meals m
LEFT JOIN habits h
    ON h.meal_id = m.id
    AND h.user_id = $1
    AND h.habit_date::date = $2::date
ORDER BY m.id
`

type GetHabitsOfDayParams struct {
	UserID  int32
	Column2 time.Time
}

type GetHabitsOfDayRow struct {
	ID       sql.NullInt64
	MealName string
	Status   string
}

func (q *Queries) GetHabitsOfDay(ctx context.Context, arg GetHabitsOfDayParams) ([]GetHabitsOfDayRow, error) {
	rows, err := q.db.QueryContext(ctx, getHabitsOfDay, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHabitsOfDayRow
	for rows.Next() {
		var i GetHabitsOfDayRow
		if err := rows.Scan(&i.ID, &i.MealName, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerHabit = `-- name: RegisterHabit :exec
INSERT INTO habits (user_id, habit_date, completed, meal_id)
VALUES ($1, $2, $3, $4)
`

type RegisterHabitParams struct {
	UserID    int32
	HabitDate time.Time
	Completed bool
	MealID    int32
}

func (q *Queries) RegisterHabit(ctx context.Context, arg RegisterHabitParams) error {
	_, err := q.db.ExecContext(ctx, registerHabit,
		arg.UserID,
		arg.HabitDate,
		arg.Completed,
		arg.MealID,
	)
	return err
}
