// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: meal_times.sql

package database

import (
	"context"
	"time"
)

const getMealTimes = `-- name: GetMealTimes :one
SELECT id, user_id, breakfast, lunch, dinner, created_at, updated_at FROM meal_time WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetMealTimes(ctx context.Context, userID int32) (MealTime, error) {
	row := q.db.QueryRowContext(ctx, getMealTimes, userID)
	var i MealTime
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Breakfast,
		&i.Lunch,
		&i.Dinner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const registerMealTime = `-- name: RegisterMealTime :one
INSERT INTO meal_time (user_id, breakfast, lunch, dinner)
VALUES ($1, $2, $3, $4) RETURNING id, user_id, breakfast, lunch, dinner, created_at, updated_at
`

type RegisterMealTimeParams struct {
	UserID    int32
	Breakfast time.Time
	Lunch     time.Time
	Dinner    time.Time
}

func (q *Queries) RegisterMealTime(ctx context.Context, arg RegisterMealTimeParams) (MealTime, error) {
	row := q.db.QueryRowContext(ctx, registerMealTime,
		arg.UserID,
		arg.Breakfast,
		arg.Lunch,
		arg.Dinner,
	)
	var i MealTime
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Breakfast,
		&i.Lunch,
		&i.Dinner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMealTime = `-- name: UpdateMealTime :one
UPDATE meal_time SET breakfast = $2, lunch = $3, dinner = $4 WHERE user_id = $1 RETURNING id, user_id, breakfast, lunch, dinner, created_at, updated_at
`

type UpdateMealTimeParams struct {
	UserID    int32
	Breakfast time.Time
	Lunch     time.Time
	Dinner    time.Time
}

func (q *Queries) UpdateMealTime(ctx context.Context, arg UpdateMealTimeParams) (MealTime, error) {
	row := q.db.QueryRowContext(ctx, updateMealTime,
		arg.UserID,
		arg.Breakfast,
		arg.Lunch,
		arg.Dinner,
	)
	var i MealTime
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Breakfast,
		&i.Lunch,
		&i.Dinner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
