// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Appointment struct {
	ID              int64
	UserID          int32
	AppointmentDate time.Time
	Completed       bool
}

type Habit struct {
	ID        int64
	UserID    int32
	HabitDate time.Time
	Completed bool
	MealID    int32
}

type Meal struct {
	ID       int32
	MealName string
}

type MealTime struct {
	ID        int32
	UserID    int32
	Breakfast time.Time
	Lunch     time.Time
	Dinner    time.Time
	CreatedAt time.Time
	UpdatedAt sql.NullTime
}

type User struct {
	ID           int32
	Name         string
	Email        string
	PasswordHash string
	BirthDate    time.Time
	Gender       string
	CreatedAt    time.Time
	UpdatedAt    sql.NullTime
}

type UserSetting struct {
	ID          int32
	UserID      int32
	WaitMinutes int32
	CreatedAt   time.Time
	UpdatedAt   sql.NullTime
}
