// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_settings.sql

package database

import (
	"context"
)

const registerUserSetting = `-- name: RegisterUserSetting :exec
INSERT INTO user_settings (user_id, wait_minutes)
VALUES ($1, $2)
`

type RegisterUserSettingParams struct {
	UserID      int32
	WaitMinutes int32
}

func (q *Queries) RegisterUserSetting(ctx context.Context, arg RegisterUserSettingParams) error {
	_, err := q.db.ExecContext(ctx, registerUserSetting, arg.UserID, arg.WaitMinutes)
	return err
}

const updateUserSetting = `-- name: UpdateUserSetting :exec
UPDATE user_settings
SET wait_minutes = $2
WHERE user_id = $1
`

type UpdateUserSettingParams struct {
	UserID      int32
	WaitMinutes int32
}

func (q *Queries) UpdateUserSetting(ctx context.Context, arg UpdateUserSettingParams) error {
	_, err := q.db.ExecContext(ctx, updateUserSetting, arg.UserID, arg.WaitMinutes)
	return err
}
