// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_settings.sql

package database

import (
	"context"
)

const getUserSetting = `-- name: GetUserSetting :one
SELECT wait_minutes
FROM user_settings
WHERE user_id = $1
`

func (q *Queries) GetUserSetting(ctx context.Context, userID int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, getUserSetting, userID)
	var wait_minutes int32
	err := row.Scan(&wait_minutes)
	return wait_minutes, err
}

const registerUserSetting = `-- name: RegisterUserSetting :exec
INSERT INTO user_settings (user_id, wait_minutes)
VALUES ($1, $2)
`

type RegisterUserSettingParams struct {
	UserID      int32
	WaitMinutes int32
}

func (q *Queries) RegisterUserSetting(ctx context.Context, arg RegisterUserSettingParams) error {
	_, err := q.db.ExecContext(ctx, registerUserSetting, arg.UserID, arg.WaitMinutes)
	return err
}

const updateUserSetting = `-- name: UpdateUserSetting :one
UPDATE user_settings
SET wait_minutes = $2
WHERE user_id = $1 RETURNING wait_minutes
`

type UpdateUserSettingParams struct {
	UserID      int32
	WaitMinutes int32
}

func (q *Queries) UpdateUserSetting(ctx context.Context, arg UpdateUserSettingParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, updateUserSetting, arg.UserID, arg.WaitMinutes)
	var wait_minutes int32
	err := row.Scan(&wait_minutes)
	return wait_minutes, err
}
